name_code_map = {
0: "macular neovascularization",
 1: "dry age-related macular degeneration",
 2: "cystoid macular edema",
 3: "unremarkable changes",
 4: "central serous chorioretinopathy",
 5: "pachychoroid pigment epitheliopathy",
 6: "other",
 7: "retinal pigment epithelial detachment",
 8: "uveitis",
 9: "chorioretinal scar",
 10: "choroidal mass",
 11: "diabetic retinopathy",
 12: "myopia",
 13: "chorioretinal atrophy",
 14: "branch retinal vein occlusion",
 15: "retinal vein occlusion",
 16: "epiretinal membrane",
 17: "proliferative diabetic retinopathy",
 18: "central retinal vein occlusion",
 19: "central retinal artery occlusion",
 20: "polypoidal choroidal vasculopathy",
 21: "retinal arterial macroaneurysm",
 22: "retinal dystrophy",
 23: "leakage",
 24: "staining",
 25: "no",
 26: "pooling",
 27: "window defect",
 28: "4",
 29: "5",
 30: "yes",
 31: "nasal",
 32: "superior",
 33: "superior nasal",
 34: "temporal",
 35: "inferior nasal",
 36: "superior temporal",
 37: "inferior temporal",
 38: "inferior",
 39: "superotemporal",
 40: "diffuse",
 41: "disc",
 42: "inferior to disc",
 43: "superior to disc",
 44: "temporal to disc",
 45: "nasal to disc",
 46: "periphery",
 47: "venular",
 48: "subretinal",
 49: "intraretinal",
 50: "preretinal",
 51: "blockage",
 52: "capillary non-perfusion",
 53: "nan",
 54: "tortuous",
 55: "microaneurysm",
 56: "intraretinal microvascular abnormalities",
 57: "venous beading",
 58: "retinal neovascularization elsewhere",
 59: "collateral vessel",
 60: "telangiectasia",
 61: "vasculitis",
 62: "retinal neovascularization of the disc",
 63: "optociliary shunt",
 64: "vessel dilation",
 65: "macroaneurysm",
 66: "mild tortuous vessel",
 67: "tortuous dilate",
 68: "pcv",
 69: "polyp",
 70: "petaloid",
 71: "ink blot",
 72: "smoke stack",
 73: "branching neovascular network",
 74: "panretinal photocoagulation",
 75: "laser scar",
 76: "retinal pigment epithelial tear",
 77: "light bulb",
 78: "starry sky",
 79: "segmental panretinal photocoagulation",
 80: "drusen"}
code_name_map = { value:key for key, value in name_code_map.items() }
cname_code_map = {
 0: "黄斑新生血管形成",
 1: "干性年龄相关性黄斑变性",
 2:"黄斑囊样水肿",
 3:"不起眼的变化",
 4:"中枢性浆液性脉络膜视网膜病变",
 5:"厚绒毛样色素上皮病",
 6: "其他",
 7:"视网膜色素上皮脱离",
 8:"葡萄膜炎",
 9:"脉络膜视网膜瘢痕",
 10:"脉络膜肿块",
 11:"糖尿病视网膜病变",
 12: "近视",
 13:"脉络膜视网膜萎缩",
 14:"视网膜分支静脉阻塞",
 15:"视网膜静脉阻塞",
 16:"视网膜前膜",
 17:"增殖性糖尿病视网膜病变",
 18:"视网膜中央静脉阻塞",
 19:"视网膜中央动脉阻塞",
 20:"息肉样脉络膜血管病变",
 21:"视网膜动脉大动脉瘤",
 22:"视网膜营养不良",
 23:"泄漏",
 24: "染色",
 25: "不",
 26: "池化",
 27: "窗口缺陷",
 28: "4",
 29: "5",
 30: "是",
 31: "鼻腔",
 32: "上级",
 33: "上鼻",
 34: "时间",
 35: "下鼻",
 36: "上颞",
 37: "下颞",
 38:"劣等",
 39:"超颞时",
 40:"漫射",
 41:"光盘",
 42:"不如光盘",
 43:"优于光盘",
 44:"时间到圆盘",
 45:"鼻到椎间盘",
 46:"外围",
 47:"静脉",
 48:"视网膜下",
 49:"视网膜内",
 50:"视网膜前",
 51:"堵塞",
 52:"毛细管非灌注",
 53:"非",
 54:"曲折",
 55:"微动脉瘤",
 56:"视网膜内微血管异常",
 57:"静脉串珠",
 58:"其他地方的视网膜新生血管形成",
 59:"抵押船",
 60:"毛细血管扩张",
 61:"血管炎",
 62:"视盘视网膜新生血管形成",
 63:"视睫分流",
 64:"血管扩张",
 65:"巨动脉瘤",
 66:"温和曲折的容器",
 67:"曲折扩张",
 68: "PCV",
 69:"息肉",
 70:"花瓣",
 71:"墨迹",
 72:"烟囱",
 73:"分支新生血管网络",
 74:"全视网膜光凝",
 75:"激光疤痕",
 76:"视网膜色素上皮撕裂",
 77:"灯泡",
 78:"星空",
 79:"节段性全视网膜照片",
 80: "玻璃疣"
}